### ISSUE TITLE
Documenter le fonctionnement de l'API

### ISSUE THREAD

**Issue by pierrelaburthe** [Logora/LogoraDocumentation#7]
Plusieurs titres nous demandent comment utiliser l'API et la page existante n'est pas assez explicative pour leur envoyer telles quelles. 

Rédiger un article de documentation expliquant dans quels cas c'est intéressant d'utiliser l'API (récupération des données, refonte du design, autre cas possibles). 

Pour la refonte du design, expliquer en détail le fonctionnement de chaque route importante et donner des exemples d'utilisation quand cela existe (Der Spiegel).

**Comment by hboisgibault** [comment]
ajouté une description sur l'autorisation.
